# Generated by Django 4.0.4 on 2022-04-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descrription', models.CharField(max_length=50, verbose_name='توضيحات')),
                ('rate', models.IntegerField(verbose_name='امتياز')),
                ('price', models.IntegerField()),
                ('time', models.IntegerField(verbose_name='زمان لازم')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاريخ انتشار')),
                ('photo', models.ImageField(upload_to='foods/')),
            ],
        ),
    ]
