# Generated by Django 4.0.4 on 2022-04-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_foof',
            field=models.CharField(choices=[('B', 'صبحانه'), ('D', 'نوشيدني'), ('DI', 'شام'), ('L', 'ناهار')], default='D', max_length=10, verbose_name='نوع غذا'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(verbose_name='(تومان) قيمت'),
        ),
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='امتياز'),
        ),
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.IntegerField(verbose_name=' زمان لازم براي پخت'),
        ),
    ]
