# Generated by Django 4.0.4 on 2022-04-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_rename_type_foof_food_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('breakfast', 'صبحانه'), ('drinks', 'نوشيدني'), ('dinner', 'شام'), ('lunch', 'ناهار')], default='drinks', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
