# Generated by Django 4.0.4 on 2022-05-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tegs',
            new_name='tags',
        ),
    ]
